env:
  global:
  - secure: "P6zKuaQ7gE0vAztiVNImlLtQIikFva6SwANRIqe1YPlcipU1xKiYo2UR/5kxQ/Y9nm0f102JOKRB98NDZrRqkUBLya+xP+2/eOE2tzMxOhd9ShfuJZeVxHv0lFFgtQqJTdFUnFCNxQR5s+C0Keer/9CtpiMAOlrw4YLq7o60op/SocuvaAzQtGnXkrN705zWhbrNDPBTPhjMS6Izt+szafP9CaluRy86UMhQh8zM4O4N2k0XSY4MPLhwTDTGoCrOUZM0u3m272ZxmdJJ7GKztYBhXN/HbENyH8UUfx76EsLq0PifqMxbnN3HZ74/E0oXB0FgDk4yOU9x8n8I83MD68DUbiSmzywrcbAKLEMNCZ77Ym89dKpiZcB2ecsAhlZ4wBimqGky9nzygBY2aQjjyv2yKy81eTeKdN72OVB9J0OIweOkN8hz/oEzGNlw0SfMOtgE5rgowS68GPKgQIPYZWqpzBHlwFeeFFLMeVf55OtEORBOcw6tmDfUCdKfZY53LrfG+LnVapsvyMCmGc97zytkptKnCq1geqLHRRjNTQyB0sFG89ejeQSVm3RqofaBQKd6cPSYGu0Yuk3CmY83ZG6ulewlheiJTciWfcC6QCZF4Y1ql9tuFJJVb1cIrkqbZr7rGJn4WDBqGPB2mQwtt5m/gK3Uh0perRSw8VSCq2o="
  - secure: "jzCoXK48uOuJUw4T0+HbA0CAdTY0Jaf24HXZHnwyEhjZoxjP+bLNxKI3UrWzvovYJ3jakmPwExm0hUXfYXVg6N8LTr3KDM0A1qFmE3K86tfUagciLD6einNtCV2TmL1jHQ1CePCoIWiGQz5LozHyycMdMeVW1ZCl+OdbjhLJdR7+Y4j0LeTPR+Wl3WcXhpX0x1amtsBBX4XoW858kWdOCTgZ/v3fmlkav5IF6UsfeW4MKfogUukXgNXi+Q87vGH3XY4yD/7luBce0QcR87hXxBYFCWcloQpyjwCtvTvLrlI6rl/peARzWA3tyBSiUseOakm8+4Tv5aq51Tsd+FFzY0Mb1N1cHHS6XGY4y6XHCYdse50UA5V40yza2i57Az7PfP+e4u7/6IMWoLNSh3xdXldkZc9atATRkJRCKlUFmh/pcW2vS2w+bdMksgjXc26GE3BrhYGLV4enVqtROEe2ndEdllHUp5DMQvqQN6GxRzS/GfYc5uJTbATK1LjIe++beg2zL2nWZ+E+xpcNriWw9whztaN0hvn8E0TND5WULElxCxrx02/katJKNk2gDGGMmprpX4q/xg/DlsHAGZhw9sODQhVidgei1IgWFU0u9nOYF0Tt3kZ67rivfwVbobcJXRrioXfWn/xXCLkLq4TklNZea6qRqaPJn+E6ybiV7Jg="
services:
- docker
script:
- docker build -t openhab-cloud .
after_success:
- if [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:latest;
    docker push $TRAVIS_REPO_SLUG:latest;
  fi
- if [[ -n "$TRAVIS_TAG" ]] && [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker login -u $DOCKER_USER -p $DOCKER_PASSWORD;
    docker tag openhab-cloud $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
  fi
