version: '2'
services:
    app:
      container_name: app
      image: openhab/openhabcloud-app:latest
      # build: . // uncomment this line for local testing
      working_dir: /opt/openhabcloud
      volumes:
      - ./config-docker.json:/opt/openhabcloud/config.json
      networks:
      - ohcloud-network
      links:
      - mongodb
      - redis
      ports:
      - "3000"
      depends_on:
      - mongodb
      - redis  
      restart: always
      labels:
      - "traefik.docker.network=ohcloud-network"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:<your-host-name>"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    mongodb:
      container_name: mongodb
      image: mongo:4.1.10-bionic
      ports:
      - "27017"
      networks:
      - ohcloud-network
      #volumes:
      #- <your local disk path>:/data/db
      restart: always
    redis:
      container_name: redis
      image: bitnami/redis:latest
      networks:
      - ohcloud-network
      ports:
      - "6379"
      environment:
      - REDIS_PASSWORD=123_openHAB
      restart: always
    traefik:
      container_name: traefik
      image: traefik:1.7
      networks:
      - internet
      - ohcloud-network
      ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
      volumes:
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  internet:
    external:
      name: internet
  ohcloud-network:
    driver: bridge